<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <UserSecretsId>1e462ac5-0da4-47ab-85f8-4bc550139bfd</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <PropertyGroup>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <PropertyGroup>
    <BrotliCompressionLevel>11</BrotliCompressionLevel>
    <CompressionExcludePatterns>**/play/**/build/*.br</CompressionExcludePatterns>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="wwwroot/play/**/build/*.wasm.br">
      <ContentType>application/wasm</ContentType>
    </Content>
    <Content Update="wwwroot/play/**/build/*.framework.js.br">
      <ContentType>text/javascript</ContentType>
    </Content>
    <Content Update="wwwroot/play/**/build/*.data.br">
      <ContentType>application/octet-stream</ContentType>
    </Content>
    <Content Update="wwwroot/play/**/build/*.symbols.json.br">
      <ContentType>application/json</ContentType>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fydar.AspNetCore.CSP\Fydar.AspNetCore.CSP.csproj" />
    <ProjectReference Include="..\Fydar.AspNetCore.OpenGraph\Fydar.AspNetCore.OpenGraph.csproj" />
    <ProjectReference Include="..\Fydar.AspNetCore.Socials\Fydar.AspNetCore.Socials.csproj" />
    <ProjectReference Include="..\Fydar.Dev.Services.EmailTickets\Fydar.Dev.Services.EmailTickets.csproj" />
    <ProjectReference Include="..\Fydar.Dev.WebApp.Client\Fydar.Dev.WebApp.Client.csproj" />
    <ProjectReference Include="..\Fydar.Dev.WebApp.Toolkit.Icons\Fydar.Dev.WebApp.Toolkit.Icons.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.CertificateManager" Version="4.0.102" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.100.8" />
    <PackageReference Include="AWSSDK.SimpleEmail" Version="4.0.100.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.11" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>
  
</Project>
